In [1]:
import torch
# Create Tensor in GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
x = torch.rand(5, 3).cuda(device=device)

y = torch.rand(5, 3).cuda(device=device)

# Add two tensors
z = x + y

# Multiply two tensors
z = x * y

# Create Tensor in CPU


# x=x.to('cpu')

x.view(3,5)
y = y.view(1,15)
y #view is used to change dimension of Array
# x = torch.rand(500, 3)

tensor([[0.7209, 0.6818, 0.6597, 0.1681, 0.1933, 0.8446, 0.9580, 0.5524, 0.3327,
         0.3172, 0.0236, 0.2881, 0.3359, 0.4647, 0.2711]], device='cuda:0')

In [26]:
x,y,z

(tensor([[0.9537, 0.0260, 0.6938],
         [0.8048, 0.7529, 0.6489],
         [0.9388, 0.5025, 0.3051],
         [0.8198, 0.1100, 0.9250],
         [0.3323, 0.7950, 0.2505]], device='cuda:0'),
 tensor([[0.0221, 0.0987, 0.6055],
         [0.6901, 0.5003, 0.6683],
         [0.2110, 0.0549, 0.0869],
         [0.0396, 0.5597, 0.4842],
         [0.0616, 0.2345, 0.9398]], device='cuda:0'),
 tensor([[0.9758, 0.1247, 1.2993],
         [1.4950, 1.2532, 1.3173],
         [1.1498, 0.5574, 0.3919],
         [0.8594, 0.6698, 1.4092],
         [0.3939, 1.0295, 1.1903]], device='cuda:0'))